version: '3'
services:
  sqlserver:
    container_name: sqlserver-db
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_12
    volumes:
      - /home/vagrant:/home/vagrant
      - /home/vagrant/work:/work
